version: '2'
services:
  jhi_mvnw-app:
    image: jhi_mvnw
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhi_mvnw-postgresql:5432/jhi_mvnw
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhi_mvnw-postgresql:
    extends:
      file: postgresql.yml
      service: jhi_mvnw-postgresql
